### ISSUE TITLE
Installer interlocks and freezes inside of Gnome-boxes

### ISSUE THREAD

**Issue by cat-master21** [crystal-linux/jade-gui#11]
**Describe the bug**
When getting to the user setup section, 

**To Reproduce**
- 1 download the latest stable release iso
- 2 run this in gnome boxes with 4-8gb of ram to make sure there is enough
- 3 startup the installer and go through the install like normal
- 4 see that it eventually stops being responsive

**Expected behavior**
The entire box/vm seemingly stops

**Additional context**
I used gnome-boxes `42.3-17184268` in the latest flatpak release on Fedora 36.

**Comment by orowith2os** [comment]
How's the RAM usage before it locks up? Any error logs saved on the VM?

**Comment by cat-master21** [comment]
I gave it 8gb of ram and it ate it up right at the keyboard screen in under 30 seconds taking about a entire gb nearly a second. Before only about 990mb was taken before jade-gui.

**Comment by cat-master21** [comment]
Also pic
![Screenshot from 2022-08-05 18-32-37](https://user-images.githubusercontent.com/96554164/183228364-a06af29d-627b-4b0d-a216-45217e70abba.png)
You can see in gnome moniter in the picture, the left handy side the ram increase signifigantly.

**Comment by orowith2os** [comment]
*maybe* a RAM leak, have you tried giving it more RAM, and possibly swap?

**Comment by cat-master21** [comment]
Gave it my entire disk as swap and:
![Screenshot from 2022-08-05 18-42-31](https://user-images.githubusercontent.com/96554164/183228699-a035bd9c-8b4f-485a-9de4-bdc39d204a78.png)
It ate all of both the combined **15.8gb** swap and ram!

**Comment by orowith2os** [comment]
Gonna blame it on a RAM leak, then. @axtloss might be able to help more than I can from here.

**Comment by cat-master21** [comment]
Oh, and also for a split second I managed to quit it, it still took all of the ram when no apps including jade-gui was running!

**Comment by mchalunderscore** [comment]
Hi, this is actually the repository for the new `jade-gui` installer written in Python with libadwaita, the old repository is https://github.com/crystal-linux/jade_gui, and it's currently archived because we're officially deprecating it

If you want to try the new installer, we've just released a testing ISO at https://github.com/crystal-linux/iso/releases/tag/08-05-22-19-35, so please give that a try for a more coherent and up-to-date Crystal experience!
