### ISSUE TITLE
[FEATURE]: Package new-enough libadwaita using pacman

### ISSUE THREAD

**Issue by SomethingGeneric** [crystal-linux/jade-gui#23]
### Is your feature request related to a problem? Please describe.

It seems like using flatpak install depends in the iso script can cause issues.

### Describe the solution you'd like

Could we ship a git-based libadwaita package that would allow us to not use pacman?

### Describe alternatives you've considered

n/a

**Comment by axtloss** [comment]
What issues does it give? Installing libadwaita-git on the iso would probably give way more issues than flatpak could possibly make.

**Comment by mchalunderscore** [comment]
Yeah the Flatpak installation in the ISO works perfectly, I'm not sure what said issue is?

**Comment by SomethingGeneric** [comment]
MB after all it was just a warning message i saw in the build process
