### ISSUE TITLE
[BUG]: Typos in the installer

### ISSUE THREAD

**Issue by orowith2os** [crystal-linux/jade-gui#24]
### Describe the bug

In the installer, there are currently a few typos. Tested using the latest iso from the GitHub releases page.

### To reproduce the bug

Install as normally, but read the options.

### Expected behavior

Capitalization would be correct.

### Screenshots

https://cdn.discordapp.com/attachments/841524327626571778/1013635007337734164/unknown.png

**Comment by SomethingGeneric** [comment]
@orowith2os can we consider this closed?

**Comment by orowith2os** [comment]
Ill have to give an updated installer a try first to ensure that its all good

**Comment by axtloss** [comment]
This was fixed by #27
