### ISSUE TITLE
[RFC]: Ignore the additional restart menu during installation

### ISSUE THREAD

**Issue by orowith2os** [crystal-linux/jade-gui#25]
### Date proposed

August 28, 2022

### Short summary

When the user installs Crystal and hits Reboot at the end of installation, it shows (GNOME's) restart menu. 

### Motivation

Seems a bit weird to have the Reboot button be clicked and hit Restart on another menu, when just one would be required.

### Changes

Reboot on the Reboot button in jade-gui, rather than showing another menu to reboot.

### Drawbacks

Might be a bit of a PITA to implement without using `sudo reboot now`, but I don't know all of the methods on how this could be done.

### Alternatives

n/a

### Unanswered questions

n/a

**Comment by axtloss** [comment]
I made it give that prompt on purpose so that the user knows what they're doing, in my experience just immediatly rebooting without an extra confirmation or a delay can be very frustrating.
Although to skip the dialog and reboot without root priviliges just 'systemctl reboot' would work

**Comment by orowith2os** [comment]
Maybe, when the user hits Reboot on the final page of installation, a countdown (that can be cancelled) could be included into jade-gui, rather than using GNOME's?

**Comment by axtloss** [comment]
That just complicates things and doesn't give any advantage

**Comment by orowith2os** [comment]
The issue I'm seeing is that it seems a bit redundant to have a Reboot button inside of jade, and then the DE's option to reboot. If the DE's option could be hidden, that would work. I don't see any issue with this, since there's nothing to click the Reboot button for you at the end of installation

**Comment by axtloss** [comment]
The restart button is highlited with the "recommended action" class internally, people aren't really expected to actually read what the button says, many will just click on it. An extra confirmation is necessary in this case.
