### ISSUE TITLE
[BUG] Back button non-functional

### ISSUE THREAD

**Issue by mchalunderscore** [crystal-linux/jade-gui#4]
**Describe the bug**
Back button does not function

**To Reproduce**
1. Open `jade-gui` as normal
2. Try to press Back on any menu

**Expected behavior**
Back button would return you to the previous menu

**Comment by axtloss** [comment]
Fixed by commit https://github.com/crystal-linux/jade-gui/commit/51eb4ebf4c6ba4a673773879b483c62eca87f61b
