### ISSUE TITLE
[BUG]: Fail if no interent

### ISSUE THREAD

**Issue by SomethingGeneric** [crystal-linux/jade-gui#44]
### Describe the bug

jade/jade-gui do not show anything visible to the user warning about needing an internet connection

### To reproduce the bug

Use jade-gui w/o ethernet or wifi

### Expected behavior

Some kind of visual warning (or even better, disable the "let's go" button

**Comment by axtloss** [comment]
fixed in https://github.com/crystal-linux/jade-gui/commit/6d4a71be6bd3adede8eb790c77c0c12ce311fd31
