### ISSUE TITLE
[FEATURE] Internally rename `jadegui` -> `jade-gui` to match package name

### ISSUE THREAD

**Issue by mchalunderscore** [crystal-linux/jade-gui#6]
**Is your feature request related to a problem? Please describe.**
Internally rename `jadegui` -> `jade-gui` to match package name, as internally the app is called jadegui

**Describe the solution you'd like**
Refactor all instances of `jadegui` into `jade-gui` internally

**Describe alternatives you've considered**
N/A

**Comment by axtloss** [comment]
resolved by https://github.com/crystal-linux/jade-gui/commit/24c758d162734a4ce17c4c901f6bf438ab5af71b
