### ISSUE TITLE
[FEATURE] Add apply button to Locale/Keymap selection

### ISSUE THREAD

**Issue by mchalunderscore** [crystal-linux/jade-gui#7]
**Is your feature request related to a problem? Please describe.**
When returning from Summary to Locale/Keymap selection, you cannot proceed as your previous choices are already selected

**Describe the solution you'd like**
This can be solved by making the selection apply not on select, but on the click of an Apply button

**Describe alternatives you've considered**
N/A

**Comment by axtloss** [comment]
Fixed in https://github.com/crystal-linux/jade-gui/commit/aeaecb7b3072d18af9b75f704e9b1db8ffe68a09
